@startuml "Diagrama de clases"
header Diagrama de clases de casos de uso
title  Presentar Examen 
footer equipo 3

skinparam style strictuml
skinparam ClassBackGroundColor EEEEEE
skinparam ClassBorderThickness 1.5
skinparam dpi 300

class InstructionsView <<JFrame>>{
    -JLabel instructionsTitle
    -TextView instructionsText
    -Button acceptInstructions
    -Button declineInstructions
}

class Button <<JButton>>{
}

class RadioButton <<JRadioButton>>{    
}

class TextView <<JPanel>>{
    -JTextArea text
}

class TextLine <<JLabel>>{
    -JLabel lineText
}

class TakeExamController{    
    +startExam()
    +evaluateStudentAnswers()
}

class TakeExamView <<JFrame>>{ 
    -JLabel title   
}

class TakeExamViewLeftSide <<JPanel>>{
    -Button finishExam
    -JLabel title
    -JLabel studentName
    -JLabel examName

}

class TimeCronometer <<JPanel>>{
    -Timer timer
    -JLabel timeLabel
}

class TakeExamViewRightSide <<JPanel>>{
    -JProgressBar questionsCounter
    -Button next
    -Button previous
}

class DomainNameLeftPanel<<JPanel>>{
}

class DomainNameRightPanel<<JPanel>>{
}

class QuestionPanel <<JPanel>>{
    
}

class AnswersPanel <<JPanel>>{

}

class Exam{
    -int examID
    -int duration
    -String instructions
    -String title
    +getExamID()
    +getDuration()
    +getInstructions()
    +getTitle()
    +setExamID()
    +setDuration()
    +setTitle()
    +setInstructions()
}

class Question{
    -int questionID
    -String questions
    -String explanation
    -int correctAnswerID
    +getCorrectAnswerID()
    +getQuestions()
    +getQuestionID()
    +getExplanation()
    +setQuestionID()
    +setExplanation()
    +setCorrectAnswerID()
    +setQuestions()
}

class Answer{
    -int answerID
    -int questionID
    -String answerDescription
    +getAnswerID()
    +getQuestionID()
    +getAnswerDescription()
    +setAnswerID()
    +setQuestionID()
    +setAnswerDescription() 
}

TakeExamController->Exam
TakeExamController-down->InstructionsView
InstructionsView-->TextView
TakeExamController->TakeExamView
TakeExamView-->TakeExamViewLeftSide
TakeExamView-->TakeExamViewRightSide
TakeExamViewRightSide-->TextView
TakeExamViewRightSide-->QuestionPanel
TakeExamViewRightSide-->AnswersPanel
TakeExamViewRightSide-->DomainNameLeftPanel
TakeExamViewRightSide-->DomainNameRightPanel
TakeExamViewRightSide-->Button
TakeExamViewLeftSide-->Button
TakeExamViewLeftSide-->TimeCronometer
DomainNameLeftPanel-->TextLine
DomainNameRightPanel-->TextLine
QuestionPanel-->TextView
AnswersPanel--"4..*"RadioButton
Exam *- "1..*" Question
Question *-down- "4..*" Answer


@enduml