@startuml "Modelo del Dominio"

title CertiComp
header "Diagrama de clases del Dominio\n"
Footer Equipo 3 

skinparam ClassBorderThickness 1
skinparam style strictuml

class Usuario{
  nombre
  apellido
  correo
  contraseña 
}
class Administrador

class Estudiante{
}

class Ayuda

class Curso{
  nombre
  descripcion
  nombreProfesores
}
class Categoria

class Examen{
  tipo
  instrucciones
  duracion
}
class Resultado{
  preguntasAprobadas
  preguntasReprobadas
}

class Pregunta{
  enunciadoPregunta
}

class Dominio

class Respuesta{
  descripcion
  esRespuestaCorrecta
  explicacion
}
class Certificado{
}

Usuario <|-up- Administrador
Usuario <|-up- Estudiante
Usuario -down- Ayuda: > consulta

Administrador -- "1..* "Examen: > crea
Administrador -right-> "     1..*"Estudiante: registra
Administrador "    1..*"-up-o Curso: administra

Estudiante "0..*"-right-"    1..*"Curso: > pertenece
Estudiante -right- "0..*"Examen: presenta
Estudiante -right- "0..*"Certificado: > recibe
Estudiante -- Resultado: > obtiene

Examen *-right- "1..*"Pregunta: contiene
Examen -up-- Resultado: > emite

Pregunta *-down- "4..*" Respuesta: tiene
Pregunta -right-o Dominio: posee

Curso "0..*" -right-o Categoria: pertenece
Curso o----- "1..*"Examen: pertenece
Curso *- Certificado: genera


@enduml