@startuml "Diagrama de clases"

title "Modelo del Dominio"

skinparam Class{
  BackgroundColor 2B2F7B-black
  AttributeFontColor white
  BorderThickness 3
  BorderColor blue
}
class Administrador{
  nombre
  apellido
  correo
  contraseña
}
class Estudiante{
  nombreEstudiante
  apellidoEstudiante
  correo
  contraseña
  cursosEstudiante
  TiposExamenesPresentados
  ultimasPreguntasAprobadas
  ultimasPreguntasReprobadas
}

class Ayuda

class Curso{
  nombreCurso
  idCurso
  participantesCurso
}
class Examen{
  tipo
  instrucciones
  duracion
  resultado
}
class Pregunta{
  enunciadoPregunta
}

class Dominio

class Respuesta{
  enunciadoRespuesta
  respuestaCorrecta
  explicacion
}
class Certificado{
  participante
  cursoParticipante
  nombreProfesores
}

Administrador -right-> "1..*       "Examen: crea
Administrador -right-> "     1..*"Estudiante: registra
Administrador "    1..*"-right-o Curso: administra

Estudiante "0..*"-right->"    1..*"Curso: pertenece
Estudiante "1..*   "-right-> "0..* "Examen: presenta
Estudiante --> Certificado: recibe
Estudiante "1..*"---> Ayuda: consulta

Examen *-down- "1..*"Pregunta: contiene
Pregunta *-down- Respuesta: tiene
Pregunta *-right- Dominio: posee

Curso o----- "1..*"Examen: pertenece
Curso *- Certificado: expide

@enduml