@startuml "Diagrama de clases"

title "Modelo del Dominio"

skinparam Class{
  BackgroundColor 2B2F7B-black
  AttributeFontColor white
  BorderThickness 3
  BorderColor blue
}
class Administrador{
  nombre
  apellido
  correo
  contraseña
}
class Usuario{
  nombreUsuario
  apellidoUsuario
  correo
  contraseña
  cedulaIdentidad
  cursosUsuario
  TiposExamenesPresentados
  ultimasPreguntasAprobadas
  ultimasPreguntasReprobadas
}
class Curso{
  nombreCurso
  idCurso
  participantesCurso
}
class Examen{
  tipo
  instrucciones
  cantidadPreguntas
  duracion
  resultado
}
class Pregunta{
  dominio
  enunciadoPregunta
}
class Respuesta{
  respuestaCorrecta
  explicacion
}
class Certificado{
  participante
  cursoParticipante
}

Administrador -down-> "    1..*"Examen: crea
Administrador -> "     1..*"Usuario: registra
Administrador "1..*"-right-o Curso: administra

Usuario "0..*"-->"    1..*"Curso: pertenece
Usuario "1..*  "-left- "1..* "Examen: presenta
(Usuario, Curso) .. Certificado: entrega

Examen *-down- "1..*"Pregunta: contiene
Pregunta *-- Respuesta: tiene

Curso o-- Examen: pertenece



@enduml