@startuml DiagramaDeEstado

title "Diagrama de estados del dominio\nEquipo 3"

state "Iniciando Proceso" as IP

[*] --> IP

state seleccionandoVista <<choice>>

IP --> seleccionandoVista: Usuario

seleccionandoVista ---> Administrando: [Admistrador]
seleccionandoVista ---> PC: [Participante]

state Administrando {

 state Administrando {

  state "Seleccionando Curso" as SC
  state "Registrar Curso" as RC
  state "Registrar Usuario" as AU
  state "Creando Examen" as CE
  [*] --> SC

  SC --> RC
  RC --> AU 
  RC --> CE
  AU --> Finalizar
  Finalizar --> [*]
  CE -->  Finalizar

}

}


state "Participando en Curso" as PC {

  state "Mostrando Opciones" as MO
  state "Editando Perfil" as Perfil{

    state "Editar Informacion" as ED
    [*]-->ED
    ED-->[*]
  }


  MO --> Perfil
  [*] --> MO
  MO --> presentarExamen
  presentarExamen ----> SE

  state "Seleccionando Examen" as SE {

    state "Mostrando Examenes Disponibles" as ME
    state "Seleccionando Tipo" as ST
    state "Mostrando Instrucciones" as MI
    state choice1 <<choice>>
    [*] --> ME
    ME --> ST
    ST --> MI
    MI --> choice1 : Acepta Instrucciones
    choice1 --> PE : Si
    choice1 --> ST : No

    state "Presentando examen" as PE {

      state "Mostrando el Enunciando de la Pregunta" as MP
      state "Respondiendo Pregunta" as RP
      state Finalizando
      state "Listando Respuestas" as LR
      [*] --> MP
      MP --> RP
      RP -left-> MP: Siguiente/Anterior
      RP -right-> Finalizando
      Finalizando --> LR
      LR --> [*]
      --

      state "Tiempo transcurriendo" as TT
      state "Tiempo detenido" as TD
      [*] -r-> TT

      TT-r-> TD : [ExamenFinalizadoTiempo]
      TT -r-> TD : [ExamenFinalizadoEleccion]
      TD -r-> [*]
    }

    state "Examen Finalizado" as ExamenTerminado
    state opciones2 <<choice>>
    PE --> opciones2 : Examen Finalizado por
    opciones2 --> ExamenTerminado : Tiempo
    opciones2 --> ExamenTerminado : Eleccion
    ExamenTerminado --> [*]

  }



}


state "Consultando ayuda" as CA {

  [*] --> SA
  state "Seleccionando ayuda" as SA
  state "Mostrando preguntas frecuentes" as MF
  state "Seleccionando pregunta" as SP
  state "Mostrando respuesta" as MR
  SA --> MF
  MF --> SP
  SP --> MR
  MR -right-> MF
  MR -left-> [*]
}



state "Finalizando Proceso" as FP
state consultarAyuda <<choice>>

Administrando --> consultarAyuda : Consultar Ayuda
PC --> consultarAyuda : Consultar Ayuda

consultarAyuda ----> CA : Si
consultarAyuda --> FP: No

CA -->FP

FP --> [*]

@enduml