@startuml Diagrama de Casos de Uso

left to right direction
skinparam actorStyle awesome

header Casos de uso
footer Equipo 3

rectangle CertiComp{

  usecase " Iniciar Sesion " as UC1 
  usecase " Registrar Usuario" as UC2
  usecase " Registrar Curso" as UC3
  usecase " Seleccionar Examen" as UC4
  usecase " Praticar Examen" as UC5
  usecase " Ver Resultado" as UC6
  usecase " Crear Examen" as UC7
  usecase " Consultar Ayuda" as UC8
  usecase " Cerrar sesion " as UC9
  usecase " Actualizar Perfil " as UC10
  
}

Administrador -up- UC7
Administrador -up- UC2
Administrador -up- UC3
Estudiante-- UC4
Estudiante-- UC5
Estudiante-- UC6

Administrador -up- UC1
Estudiante -- UC1

Administrador -up- UC9
Estudiante-- UC9


Administrador -up-  UC10
Estudiante -- UC10

Administrador -up- UC8
Estudiante -- UC8


@enduml
