@startuml Diagrama de Estado


header Estado Inicial
footer Equipo 3
title "Diagrama de estados del dominio"




state "Validando\nIdentificacion" as vi
state  "creando\nCurso" as gc
state  "creando\nExamen" as ge
state  "cargando\npregunta" as cp

state "Mostrando\nInstrucciones" as mi
state "Presentando\nExamen" as ee{
    state "mostrando pregunta" as mp
    state "Guardando Respuesta" as gp
    mp --> gp: opcion
    gp --> mp: \nSiguiente
}
state "Guardando \ny\nMostrando\nResultado" as gr
state "Actualizando\nPerfil" as ap
state "Mostrando\nAyuda" as ma
state "Incluyendo\nEstudiante" as ie
state finAd <<join>>

[*] --> vi: Iniciar Sesion
vi -left-> gc: Crear Curso\nAdministrador
gc --> ge: Crear Exmen
ge --> cp: Cargar pregunta
cp --> ie: Registrar\nEstudiante
vi --> finAd
finAd --> ma
finAd --> ap

ma --> [*]: cerrar sesion
ap --> [*]: cerrar sesion
ie -right-> [*] : cerrar sesion

 

vi -right-> mi: Iniciar Examen\nEstudiante
mi --> ee: Presentar Examen
ee --> gr: resultado
gr --> [*]:  Cerrar Sesion

@enduml