@startuml Clases Modelo de Domanio
title  Modelo de Dominio General
Header Clases
footer reto 7


abstract Persona{
    -name
    -lastName
    -id
    
}


class Usuario {
    -email
    -password
/'    +{method} setPass(str)
    +{method} setEmail'/
}

class Administrador {
/'    +{method}setTime(idCurso, idExamen)
    +{method}set_NQuest(idCurso, idExamen)
    #{method} register(idUsuario)
'/
}

class Participante{
    +Cursos
    +Certificados

}


Class Examen{
    -time
    -nPregunta
}


Class Pregunta{
    -option
    -quest
}

Class Curso {
    -name
    -id
    -"NombreProfesor[]"
    -Instrucciones

}

Class Dominio{
    -name
}


class Certificado{
    -fecha
}

Persona <|-- Usuario
Usuario <|-left- Administrador
Usuario <|-- Participante 




'------------------------------

Curso "1" *-left-"1..*" Examen
note top of Curso : <b>1</b> o <b>mas</b> examenes\n<b>son parte elemental\nde un curso
Examen "1" *-- "1..*" Pregunta
note left of Examen :  <b>1</b> examen tiene\n<b>1</b> o mas\npreguntas
note right of Pregunta : <b>1 o mas son\nparte de\n<b>1 examne
Dominio "1..*"*-right- "1" Pregunta
note top of Dominio: <b>una pregunta\npertenece a\n<b>1 o mas Dominios

'-----------------------------


Curso "1..*" o-right- "0..*" Participante
note right of Participante: <b>Es participante el\n<b>que esta en\n<b>un curso\n<b>Un Curso tiene\n<b>0 o mas Participantes
Administrador "1" *-- "1..*" Curso
'note left of Administrador: <b>Un o mas</b> Administrador es\nImparten <b>1 o</b>\n<b>mas</b> Cursos
Curso -- Certificado: > Emite
Participante -- Certificado: < Recibe






@enduml