@startuml "Relaición de Estados de Casos de Usos"


title Estados de casos de usos\nEstudiante
header Casos de uso
Footer Equipo 3
skinparam width 300
left to right direction

state "autenticando" as au
state "presentando examen" as pe
state "mostrando resultados" as mr
state "generando certificado" as gc


[*] -r-> au : Inicio de sesión
au --> pe: Presentar Examen
pe --> mr: Resultado
mr --> pe: Presentar Examen
mr -r-> gc: Generar Certificado

gc -r-> [*]: Cerrar Sesion


