@startuml "Diagrama de colaboracion"

title "Caso de uso: Presentar Examen"

left to right direction

skinparam Dpi 300
skinparam EntityBackgroundColor white
skinparam BoundaryBackgroundColor white
skinparam ControlBackgroundColor white
skinparam ActorBackgroundColor white

header Análisis y Colaboración
footer Equipo 3

actor "Student" as std
boundary "ExamsListView" as ELV
boundary "InstructionsView" as IV
boundary "TakeExamView" as TEV
boundary "ResultsView" as RV
control "TakeExamController" as TEC
entity "Student" as stde
entity "Exam" as ex
entity "Question" as que



std--->ELV
ELV-IV
IV---TEC
TEV---TEC
RV---TEC
TEC--stde
TEC--ex
ex-que

@enduml