state ActualizarPerfil{

  state actualizarDatos: se permite editar la informacion
  state introduceNuevosDatos: introduce su nuevo correo y/o nueva contraseña
  state validarInfoIngresada:  se valida la información ingresada
  state finalizarActualizacion: se guardan los cambios el nuevo correo y/o password \ny muestra un mensaje de éxito
  state A1ActualizarPerfil: Si la dirección de correo electrónico ya está en uso
  state A2ActualizarPerfil: Si la nueva contraseña ingresada no cumple los requisitos mínimos 

  [*]-->actualizarDatos

  
  actualizarDatos --> introduceNuevosDatos
  introduceNuevosDatos--> validarInfoIngresada
  validarInfoIngresada --> A1ActualizarPerfil
  A1ActualizarPerfil --> actualizarDatos
  validarInfoIngresada --> A2ActualizarPerfil
  A2ActualizarPerfil --> actualizarDatos
  validarInfoIngresada --> finalizarActualizacion
  finalizarActualizacion --> [*]

}