@startuml DiagramaDeEstadoAdmin

title "Diagrama de estados del dominio\nEquipo 3"

state "Iniciando Proceso" as IP

[*] --> IP

IP --> Administrando

state Administrando {

  state "Seleccionando Curso" as SC
  state "Registrar Curso" as RC
  state "Registrar Usuario" as AU
  state "Creando Examen" as CE
  [*] --> SC

  SC --> RC
  RC --> AU 
  RC --> CE
  AU --> Finalizar
  Finalizar --> [*]
  CE -->  Finalizar

}

state "Consultando ayuda" as CA {

  [*] --> SA
  state "Seleccionando ayuda" as SA
  state "Mostrando preguntas frecuentes" as MF
  state "Seleccionando pregunta" as SP
  state "Mostrando respuesta" as MR
  SA --> MF
  MF --> SP
  SP --> MR
  MR -right-> MF
  MR -left-> [*]
}



state "Finalizando Proceso" as FP
@startuml DiagramaDeEstadoAdmin

title "Diagrama de estados del dominio\nEquipo 3"

state "Iniciando Proceso" as IP

[*] --> IP

IP --> Administrando

state Administrando {

  state "Seleccionando Curso" as SC
  state "Registrar Curso" as RC
  state "Registrar Usuario" as AU
  state "Creando Examen" as CE
  [*] --> SC

  SC --> RC
  RC --> AU 
  RC --> CE
  AU --> Finalizar
  Finalizar --> [*]
  CE -->  Finalizar

}

state "Consultando ayuda" as CA {

  [*] --> SA
  state "Seleccionando ayuda" as SA
  state "Mostrando preguntas frecuentes" as MF
  state "Seleccionando pregunta" as SP
  state "Mostrando respuesta" as MR
  SA --> MF
  MF --> SP
  SP --> MR
  MR -right-> MF
  MR -left-> [*]
}



state "Finalizando Proceso" as FP
IP --> CA : Consultar Ayuda


CA -->FP
Administrando --> FP
FP --> [*]

@enduml


CA -->FP
Administrando --> FP
FP --> [*]

@enduml