state VerResultado{

  [*]-->mostrarRespuestas

  state mostrarRespuestas: se muestran las respuestas  del último examen y su resultado
  state revisionResultado: revisa su resultado
  state guardarResumen: se guarda un resumen de los resultados
  state A1VerResultado: Se muestran las respuestas correctas a las preguntas


  mostrarRespuestas --> revisionResultado
  mostrarRespuestas --> A1VerResultado
  revisionResultado --> guardarResumen

  guardarResumen --> [*]

}