state ConsultarAyuda{

  state solicitaAyuda:
  state preguntasFrecuentes: se  muestran preguntas frecuentes
  state preguntaProblema: selecciona la pregunta que se le asemeje a su problema
  state respuestaProblema: se muestra la respuesta solicitada
  state terminaConsulta: verifica su respuesta
  state A1ConsultarAyuda:  Si la respuesta no esta,se anota la pregunta para agregar en un futuro la respuesta 
  state A2ConsultarAyuda: Si el Estudiante decide cancelar el proceso termina el caso de uso sin hacer nada

  [*]-->solicitaAyuda
  [*]--> A2ConsultarAyuda

  A2ConsultarAyuda -->[*]

  solicitaAyuda-->preguntasFrecuentes
  preguntasFrecuentes-->preguntaProblema
  preguntaProblema-->respuestaProblema
  preguntaProblema-->A1ConsultarAyuda
  A1ConsultarAyuda-->[*]
  respuestaProblema-->terminaConsulta
  terminaConsulta-->[*]

}