state practicaExamen{
    
    [*]--->muestraExamen
    muestraExamen: se presentan las preguntas y las posibles respuestas
    muestraExamen: Se inicia el cronometro
    seleccionaRespuesta:selecciona la opcion
    seleccionaRespuesta:de respuesta a cada pregunta
    muestraExamen-->seleccionaRespuesta
    explicaRespuestas: Se da  una breve explicacion de la respuesta
    state respondOreturn <<fork>>
    seleccionaRespuesta-->respondOreturn
    concluyeExamen: 
    cronometroEnd: finaliza el examen por tiempo
    state finalizaExamne <<join>>
    explicaRespuestas-->finalizaExamne: finalizado por eleccion
    cronometroEnd-->finalizaExamne :finalizado por tiempo
    finalizaExamne-->concluyeExamen
    retrocederEnP: mostras preguntas anteriores o siguientes
   respondOreturn-->explicaRespuestas :termina de responder
   respondOreturn-->retrocederEnP :quiere ver preguntas anteriores
   retrocederEnP-->seleccionaRespuesta
    concluyeExamen---->[*]
    
}