state CrearExamen{

    
    permiteIntroducirExamen:ntipo, duracion, cantidad de preguntas,\npreguntas, respuestas y explicacion
    llenarCamposExamen: se carga toda la informacion
    finalizarCreacion:El administrador finaliza el proceso
    A1ErrorEnNumero: errores de creacion del examen
    A2cancelarCreacion: No desea crear el examen 
    [*]-->permiteIntroducirExamen
    permiteIntroducirExamen-->llenarCamposExamen
    state correctoUerror <<fork>>
    llenarCamposExamen-->correctoUerror
    correctoUerror-->finalizarCreacion :datos correctos
    correctoUerror-->A1ErrorEnNumero :datos incorrectos
    A1ErrorEnNumero-->llenarCamposExamen
    permiteIntroducirExamen-->A2cancelarCreacion
    A2cancelarCreacion-->[*]
    finalizarCreacion-->[*] :examen creado
}